### PR TITLE
Endpoints architecture 

### LINKED ISSUE #5: Backend-Frontent Communication
- Explain what data is transmitted from backend to frontend and vice versa.
- Define the backend endpoints
- Push to both backend and frontend repositories.

### PR DESCRIPTION
**Pull request by Andrei-Fabian-Pop**
Created a file that describes the endpoints needed for sprint 1 as well as the data that is being sent on them.

### CODE REVIEW

**Comment by bia1708** [comment]
I don't see here the endpoint for searching a word. It should be sent to the backend as well (for the word of the day statistic).

**Comment by Sipos-Lucas-George** [comment]
LGTM :hear_no_evil:

**Review by Sipos-Lucas-George — APPROVED** [review]

**Comment by Andrei-Fabian-Pop** [comment]
@bia1708 the endpoint for word of the day should just send the searched word or should it also send some response back?

**Comment by bia1708** [comment]
@Andrei-Fabian-Pop I don't know, honestly. Whatever you decide is fine.

**Review by bia1708 — APPROVED** [review]

**Pull request merged**
