### PR TITLE
Database Documetation

### PR DESCRIPTION
**Pull request by Andrei-Fabian-Pop**
Added the database entity relation diagram, please comment in the review weather I should provide further documentation on this topic.

### CODE REVIEW

**Comment by bia1708** [comment]
In the Accounts section, what should "instagram", "facebook" and "twitter" represent? I think you should have them as strings,  representing the account name, and also for each social media you should keep the personal access token as well.

**Comment by Andrei-Fabian-Pop** [comment]
@bia1708 They do represent the personal access token for each account from the user (1:1). Each user may or may not have their personal access token in the Accounts table. Do we really need to store their "display name" as well?

**Comment by bia1708** [comment]
@Andrei-Fabian-Pop with the purpose of having less API calls, we may store the username in the database. The user won't necessarily be prompted for it, but we can retrieve it with only one API call.  You may leave it as is for now, we might need changes in the later stages of development anyway. Also, please rename the attributes to something more intuitive (i.e. [social]_access_token).

**Comment by Sipos-Lucas-George** [comment]
@Andrei-Fabian-Pop In my opinion statistics should be a procedure on the database and not a table, but maybe we are not talking about the same statistics. Why do we need to save the user's age in database, it's not like we are going to use it anywhere, am I right? Also, the name field in the User table will be the username of one of the social medias?

**Comment by Andrei-Fabian-Pop** [comment]
@Sipos-Lucas-George I think we should keep the users age in the database as it can help us develop statistics later, for example the average age of our clients. Even if we do not use that, it will not be hindrance to anyone. As for the username, that will be the display name on our application, it does not have any correlation with the username from the other social medias.

**Review by Sipos-Lucas-George — APPROVED** [review]

**Review by bia1708 — APPROVED** [review]

**Pull request merged**
