### PR TITLE
install_script: Both bash and bat updated/added

### PR DESCRIPTION
**Pull request by Sipos-Lucas-George**
Added .bat for the users that use Windows. Please try it out and let me know if it works because I am a Linux user.

### CODE REVIEW

**Review by bia1708 — CHANGES_REQUESTED** [review]
Please set the dependency for the django version to be 3.2.23 in `packages.txt`. I ran the script locally and I get the following output:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
django-psycopg2-extension 0.1.1 requires django<4.0,>=3.1, but you have django 4.2.6 which is incompatible.
Successfully installed Django-4.2.6 asgiref-3.7.2 django-cors-headers-4.3.0 djangorestframework-3.14.0 mssql-django-1.3 psycopg2-2.9.9 pymssql-2.2.10 pyodbc-5.0.1 python-dotenv-1.0.0 pytz-2023.3.post1 sqlparse-0.4.4 typing_extensions-4.8.0
`

My current version of the packages after I made this change locally:
`asgiref==3.7.2
astroid==2.3.3
attrs==22.2.0
backports.zoneinfo==0.2.1
click==8.0.3
cmake-example==0.0.1
colorama==0.4.3
Django==3.2.23
django-cors-headers==4.3.0
django-psycopg2-extension==0.1.1
djangorestframework==3.14.0
djangorestframework-simplejwt==5.2.2
drf-spectacular==0.26.1
importlib-resources==5.12.0
inflection==0.5.1
isort==4.3.21
jsonschema==4.17.3
lazy-object-proxy==1.4.3
mccabe==0.6.1
mssql-django==1.3
numpy==1.24.3
pandas==2.0.1
pkgutil_resolve_name==1.3.10
psycopg2==2.9.9
psycopg2-binary==2.9.6
PyJWT==2.6.0
pylint==2.4.4
pymssql==2.2.10
pyodbc==5.0.1
PyQt5==5.15.4
pyqt5-plugins==5.15.4.2.2
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.0
pyqt5-tools==5.15.4.3.2
PyQt5Designer==5.14.1
pyrsistent==0.19.3
python-dateutil==2.8.2
python-dotenv==1.0.0
pytz==2023.3.post1
PyYAML==6.0
qt5-applications==5.15.2.2.2
qt5-tools==5.15.2.1.2
six==1.13.0
sqlparse==0.4.4
typing_extensions==4.8.0
tzdata==2022.7
uritemplate==4.1.1
wrapt==1.11.2
zipp==3.15.0`

**Comment by Sipos-Lucas-George** [comment]
If you look closely in the ERROR output you will see that for some reason psycorg2 0.1.1 is not compatible with django 4.2.6 and I mean there are some changes that it work but not really sure. Create venv, then activate it and after that run the script again, and run the server to see if you have anything missing "python manage.py runserver"

**Comment by bia1708** [comment]
@Sipos-Lucas-George I was just updating my commit message. The django version for windows users should be 3.2.23. Why do we need this package, anyway? Since this is a package for PostgreSQL and we've decided we won't use that anymore.

**Comment by Sipos-Lucas-George** [comment]
@bia1708 Now it should work, hopefully

**Review by bia1708 — CHANGES_REQUESTED** [review]
The error still persists.

**Comment by Sipos-Lucas-George** [comment]
@bia1708 Update your pip to the latest version and if it work I will added to packages.txt

**Comment by Sipos-Lucas-George** [comment]
Tested the code myself and it actually works for me at least, even so I added a line to upgrade the Python Install Packages before adding the requirements.

**Review by bia1708 — APPROVED** [review]

**Pull request merged**
