### PR TITLE
DB_README.md: Quick tutorial to install needed drivers for db

### PR DESCRIPTION
**Pull request by Sipos-Lucas-George**
For Django to access the database it needs a special driver made by Microsoft and this  DB_README.md is design to shorten the time of searching for the driver we're using.

### CODE REVIEW

**Comment by bia1708** [comment]
Thank you for the documentation, it's great stuff.

**Review by bia1708 — APPROVED** [review]

**Review by bia1708 — CHANGES_REQUESTED** [review]
Actually, please move this documentation inside docs/database. It makes more sense for it to be there.

**Review by bia1708 — APPROVED** [review]

**Comment by bia1708** [comment]
Sign your commit and then you can merge this into main.

**Comment by Sipos-Lucas-George** [comment]
@bia1708 it is signed, as long as I can see

**Review by Sipos-Lucas-George — COMMENTED** [review]
asd

**Pull request merged**
